spring.application.name=DAO_layer_HW
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase2
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.sql.init.mode=never
